*** Settings ***
Documentation    
Resource    ./test_connexion_r�ussie_avec_des_identifiants_valides_avec_parabank_step_definitions.resource
Metadata    Feature    Test Connexion réussie avec des identifiants valides avec ParaBank
Metadata    Generated by    _gherkin2robotframework on 2025-04-08T12:25:24.314692_

*** Test Cases ***
Test Connexion réussie avec des identifiants valides avec ParaBank
    [Tags]    POEI20252-500    POEI20252-522    WilliamLAY
    Given L'utilisateur lance la page parabank.parasoft.com
    When L'utilisateur rentre son login
    And L'utilisateur rentre son mot de passe
    And L'utilisateur clique sur le bouton login
    Then L'utilisateur est connecté à l'application SauceDemo et est redirigé sur la page d'accueil de l'application


